server:
  port: 8761  #服务端口

spring:
  application:
    name: dc-register-server   #指定服务名

eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false  #是否开启自我保护模式
    eviction-interval-timer-in-ms: 60000  #服务注册表清理间隔（单位毫秒，默认是60*1000）
  client:
    registerWithEureka: false  #服务注册，是否将自己注册到Eureka服务注册中心，单机版本时，为false就好
    fetchRegistry: false       #服务发现，是否从Eureka中获取注册信息
    serviceUrl:              #Eureka客户端与Eureka服务端的交互地址，高可用状态配置对方的地址，单机状态配置自己（如果不配置则默认本机8761端口）
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


