server:
  port: 8762 #服务端口

eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:              #Eureka客户端与Eureka服务端的交互地址，高可用状态配置对方的地址，单机状态配置自己（如果不配置则默认本机8761端口）
      defaultZone: http://peer1:8761/eureka/


